apiVersion: v1
kind: Service
metadata:
  namespace: _namespace_
  name: _modelname_-modelserver
  labels:
    app: _modelname_-modelserver
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort:  9000 
      protocol: TCP
      name: tf-serving
    - port: 8501
      targetPort:  8501
      protocol: TCP
      name: tf-restful
  selector:
    app: _modelname_-modelserver
    release: z

---
# Source: instance-modelserver/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: _namespace_
  name: _modelname_-modelserver
  labels:
    app: _modelname_-modelserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-modelserver
      release: z
  template:
    metadata:
      labels:
        app: instance-modelserver
        release: z
    spec:
      containers:
        - args:
          - /usr/bin/tensorflow_model_server
          - --port=9000
          - --rest_api_port=8501
          - --model_name=_modelname_
          - --model_base_path=/models/_modelname_
          name: _modelname_-modelserver
          image: "index.alauda.cn/alaudak8s/_modelname_-modelserver:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tf-serving
              containerPort: 9000
              protocol: TCP
            - name: tf-restful
              containerPort: 8501
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
