apiVersion: v1
kind: Service
metadata:
  namespace: @namespace@
  name: @modelname@-modelserver
  labels:
    app: @modelname@-modelserver
spec:
  type: NodePort
  ports:
    - port: @restfulport@
      targetPort:  @restfulport@ 
      protocol: TCP
      name: tf-serving
    - port: @grpcport@
      targetPort:  @grpcport@
      protocol: TCP
      name: tf-restful
  selector:
    app: @modelname@-modelserver
    release: z

---
# Source: instance-modelserver/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: @namespace@
  name: @modelname@-modelserver
  labels:
    app: @modelname@-modelserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-modelserver
      release: z
  template:
    metadata:
      labels:
        app: instance-modelserver
        release: z
    spec:
      containers:
        - args:
          - /usr/bin/tensorflow_model_server
          - --port=@restfulport@
          - --rest_api_port=@grpcport@
          - --model_name=@modelname@
          - --model_base_path=/models/@modelname@
          name: @modelname@-modelserver
          image: "index.alauda.cn/alaudak8s/@modelname@-modelserver:@modelversion@"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tf-serving
              containerPort: @restfulport@
              protocol: TCP
            - name: tf-restful
              containerPort: @grpcport@
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
