apiVersion: v1
kind: Service
metadata:
  namespace: _namespace_
  name: z-instance-modelserver
  labels:
    app: instance-modelserver
    chart: instance-modelserver-0.1.0
    release: z
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort:  9000 
      protocol: TCP
      name: tf-serving
    - port: 8501
      targetPort:  8501
      protocol: TCP
      name: tf-restful
  selector:
    app: instance-modelserver
    release: z

---
# Source: instance-modelserver/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: _namespace_
  name: z-instance-modelserver
  labels:
    app: instance-modelserver
    chart: instance-modelserver-0.1.0
    release: z
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-modelserver
      release: z
  template:
    metadata:
      labels:
        app: instance-modelserver
        release: z
    spec:
      containers:
        - args:
          - /usr/bin/tensorflow_model_server
          - --port=9000
          - --rest_api_port=8501
          - --model_name=chicago-taxi
          - --model_base_path=/models/chicago-taxi
          name: instance-modelserver
          image: "index.alauda.cn/alaudak8s/chicago-taxi-modelserver:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tf-serving
              containerPort: 9000
              protocol: TCP
            - name: tf-restful
              containerPort: 8501
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: tf-serving
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
